server:
  port: 10000
  shutdown: graceful

spring:
  application:
    name: D_M_SK01

  pid:
    file: ./application.pid

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  data:
    redis:
      lettuce:
        pool:
          max-active: 2
          max-idle: 2
          min-idle: 2

      cluster:
        nodes: 127.0.0.1:6379
        password:

file-server:
  token: HermesSteps
  image-request-uri: https://dev-storage.std-ums.com:19200/v1/storage/download
  image-download-path: /Users/simjeonghun/github/seoultel/kr.co.seoultel.message.mt.mms-direct/src/main/resources/images

heart-beat:
  host: localhost
  port: 8348
  reconnect-time: 30
  expire-time: 30


sender:
  name: D_M_SK01
  group: Direct
  telecom: skt                               # lowerCase
  is-dummy: on

  http:
    endpoint:
      ip: 127.0.0.1
      port: 10001

    bpid: null
    vas-id: "21"
    vasp-id: "1"

    cpids:
      - cpid: "1528801080"
        tps: 10
      - cpid: "1528801081"
        tps: 15
      - cpid: "1528801082"
        tps: 7
      - cpid: "1528801083"
        tps: 20
      - cpid: "1528801084"
        tps: 13



  storage:
    persistence:
      file-path: /Users/simjeonghun/github/seoultel/kr.co.seoultel.message.mt.mms-direct/src/main/resources/storage/skt/persistence.storage

    history:
      file-path: /Users/simjeonghun/github/seoultel/kr.co.seoultel.message.mt.mms-direct/src/main/resources/storage/skt/history.storage

    republish:
      file-path: /Users/simjeonghun/github/seoultel/kr.co.seoultel.message.mt.mms-direct/src/main/resources/storage/skt/republish.storage

    report:
      file-path: /Users/simjeonghun/github/seoultel/kr.co.seoultel.message.mt.mms-direct/src/main/resources/storage/skt/report.storage


mt:
  exchange: xsend.mms                                  # write to mt exchange-name
  queue: mt.sender.D_M_SK01                                     # write to mr exchange-name

mr:
  exchange: xrpt                                  # write to mt exchange-name
  queue: mr.mms.report                                   # write to mr exchange-name

rabbitmq:
  primary-cluster: off                    # if rabbit is clustered write on, else off
  primary-host: localhost
  primary-port: 5672
  primary-username: arreo
  primary-password: 1234
  primary-virtual-host: /mcmp

  secondary-cluster: off              # if rabbit is clustered write on, else off
  secondary-host: localhost
  secondary-port: 5672
  secondary-username: arreo
  secondary-password: 1234
  secondary-virtual-host: /mcmp



logging:
  charset:
    console: UTF-8